### Makefile.inc -- Project Anvil

# Author: Michael Grünewald
# Date: Mon Feb  9 22:09:02 CET 2015

# Anvil (https://github.com/michipili/anvil)
# This file is part of Anvil
#
# Copyright © 2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

# Local Variables:
# mode: makefile
# End:

### End of file `Makefile.inc'
