### Makefile -- Anvil subroutines

# Anvil (https://github.com/michipili/anvil)
# This file is part of Anvil
#
# Copyright © 2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY+=		anvil.m4
LIBRARY+=		anvil_autoconf.sh
LIBRARY+=		anvil_configuration.sh
LIBRARY+=		anvil_driver.sh
LIBRARY+=		anvil_filter.sh
LIBRARY+=		anvil_build.sh
LIBRARY+=		anvil_license.sh
LIBRARY+=		anvil_template.sh
LIBRARY+=		anvil_filterbranch.sh

SUBRDIR=		${SHAREDIR}/subr

.include "shell.lib.mk"

### End of file `Makefile'
