Document: anvil
Title: Debian anvil Manual
Author: <insert document author here>
Abstract: This manual describes what anvil is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/anvil/anvil.sgml.gz

Format: postscript
Files: /usr/share/doc/anvil/anvil.ps.gz

Format: text
Files: /usr/share/doc/anvil/anvil.text.gz

Format: HTML
Index: /usr/share/doc/anvil/html/index.html
Files: /usr/share/doc/anvil/html/*.html
